"""R-02 实验委托业务类型（通用；行业字段走可选 profile）。"""

LAB_REQUEST_TYPE_IQC = "iqc"
LAB_REQUEST_TYPE_RD = "rd"
LAB_REQUEST_TYPE_PROJECT_MATERIAL = "project_material"
LAB_REQUEST_TYPE_PROJECT_PRODUCT = "project_product"
LAB_REQUEST_TYPE_OUTSOURCE = "outsource"
LAB_REQUEST_TYPE_GENERAL = "general"

LAB_REQUEST_TYPES = frozenset(
    {
        LAB_REQUEST_TYPE_IQC,
        LAB_REQUEST_TYPE_RD,
        LAB_REQUEST_TYPE_PROJECT_MATERIAL,
        LAB_REQUEST_TYPE_PROJECT_PRODUCT,
        LAB_REQUEST_TYPE_OUTSOURCE,
        LAB_REQUEST_TYPE_GENERAL,
    }
)

LAB_REQUEST_TYPE_DEFAULT = LAB_REQUEST_TYPE_GENERAL
LAB_REQUEST_PRIORITIES = frozenset({"normal", "urgent"})
